[package]
name = "native_codec_impl"
version = "1.4.1"
authors = ["Dmytro Lytovchenko <dmytro.lytovchenko@erlang-solutions.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies.cpython]
version = "0.7.2"
features = ["extension-module"]

[dependencies]
flate2 = "1"
thiserror = "1"
